apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod-mutator
  name: pod-mutator
  namespace: webhook-poc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pod-mutator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-mutator
      namespace: webhook-poc
    spec:
      containers:
        - image: webhook-server-go:gin #This will be the webhook server docker image, you will be building with the Dockerfile.
          imagePullPolicy: IfNotPresent
          name: webhook-server
          ports:
            - containerPort: 8443
              name: 8443tcp
              protocol: TCP
          resources:
            requests:
              cpu: '1'
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: tls-cert_key
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tls-cert_key
          secret:
            defaultMode: 420
            secretName: webhook_cert_key
